### ISSUE TITLE
Does not work with the "replace" directive

### ISSUE THREAD

**Issue by deuscapturus** [adamtheturtle/sphinx-substitution-extensions#59]
Using replace
```
.. |version| replace:: 3.0-6900ee
```

 with a `substitution-code-block` does not substitute:

```
.. substitution-code-block::  yaml

  Resources:
    AutoScaleGroup:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation/templates/ec2-autoscale-|version|.yaml
```

Results:

```
Resources:
  AutoScaleGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-us-west-2.amazonaws.com/cloudformation/templates/ec2-autoscale-|version|.yaml
```
